POST http://127.0.0.1:8000/api/transactions/newnew/
Content-Type: multipart/form-data; boundary=WebAppBoundary
Cookie: csrftoken=EHh7Y5d2Ir0XLWvnCHkyLvtOkJQDF2qZaagyvvvwuOpZAgPQEIqGvsnOgglXYXOk; sessionid=5bbw9lrwrtd03eg318n5z5rb06ruxwyh

--WebAppBoundary--
Content-Disposition: form-data; name="username"

john@doe.fr
--WebAppBoundary--
Content-Disposition: form-data; name="password"

MySuperPassword
###
