POST http://127.0.0.1:8000/api/accounts/login/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary--
Content-Disposition: form-data; name="username"

john@doe.fr
--WebAppBoundary--
Content-Disposition: form-data; name="password"

MySuperPassword
###
