POST http://127.0.0.1:8000/api/accounts/registration/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"

JohnDoe
--WebAppBoundary--
Content-Disposition: form-data; name="email"

john@doe.fr
--WebAppBoundary--
Content-Disposition: form-data; name="password1"

MySuperPassword
--WebAppBoundary--
Content-Disposition: form-data; name="password2"

MySuperPassword
###
