# Generated by Django 4.0.5 on 2022-06-25 20:07

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friend_code',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=6, unique=True, verbose_name='Friend code'),
        ),
    ]
