# Generated by Django 4.0.5 on 2022-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_key',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Public Key'),
        ),
    ]
