# Generated by Django 4.0.5 on 2022-07-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_friend_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pub_key',
            new_name='pubkey',
        ),
    ]
