# Generated by Django 4.0.5 on 2022-06-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('nb_new_file', models.IntegerField(default=0, verbose_name='Number of New Files')),
                ('user1', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transaction_user1', to=settings.AUTH_USER_MODEL, verbose_name='User 1')),
                ('user2', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transaction_user2', to=settings.AUTH_USER_MODEL, verbose_name='User 2')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identification')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('checksum', models.CharField(max_length=256, verbose_name='Checksum')),
                ('times_downloaded', models.IntegerField(default=0, verbose_name='Times Downloaded')),
                ('owner', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner Id')),
                ('receiver', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiver Id')),
                ('transaction', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files', to='transactions.transaction', verbose_name='Transaction')),
            ],
        ),
    ]
