# Generated by Django 4.0.5 on 2022-06-19 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identification')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('checksum', models.CharField(max_length=256, verbose_name='Checksum')),
                ('times_downloaded', models.IntegerField(default=0, verbose_name='Times Downloaded')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Token')),
                ('nb_new_file', models.IntegerField(default=0, verbose_name='Number of New Files')),
            ],
        ),
    ]
