# Generated by Django 4.0.5 on 2022-06-19 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user1',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transaction_user1', to=settings.AUTH_USER_MODEL, verbose_name='User 1'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user2',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='transaction_user2', to=settings.AUTH_USER_MODEL, verbose_name='User 2'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files_owned', to=settings.AUTH_USER_MODEL, verbose_name='Owner Id'),
        ),
        migrations.AddField(
            model_name='file',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files_received', to=settings.AUTH_USER_MODEL, verbose_name='Receiver Id'),
        ),
        migrations.AddField(
            model_name='file',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='files', to='transactions.transaction', verbose_name='Transaction'),
        ),
    ]
