# Generated by Django 4.0.5 on 2022-06-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_file_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
