# Generated by Django 4.0.5 on 2022-06-29 08:18

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 8, 18, 15, 586231, tzinfo=utc), verbose_name='Last modification Date'),
        ),
    ]
