# Generated by Django 4.0.5 on 2022-06-29 08:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_file_creation_date_transaction_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last modification Date'),
        ),
    ]
