# Generated by Django 4.0.5 on 2022-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='nonce',
            field=models.CharField(verbose_name='File nonce', max_length=255),
        ),
    ]
