# Generated by Django 4.0.6 on 2022-07-22 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_file_nonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='modification_date',
        ),
        migrations.AddField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
